# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: nojsja
subtitle: 个人博客
author: nojsja
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://nojsja.github.io/blogs       # Note: don't forget to modify the CNAME file to your url
root: /blogs
permalink: :year/:month/:day/:abbrlink.html/
permalink_defaults:
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex

#Custom Setting Start

# Site settings
SEOTitle: nojsja | Blog
email: e-mail_address
description: "nojsja 个人博客"
keyword: ""
header-img: http://nojsja.gitee.io/static-resources/images/hexo/header_img/home.jpg?v2
article-header-img: https://nojsja.gitee.io/static-resources/images/hexo/article_header/article_header.jpg
article-img: img/article_header/article_bg.jpg
404-img: img/header_img/404.png
signature: false #show signature
signature-img: img/signature/BeanTechSign-white.png 

# SNS settings
github_username:    nojsja
jianshu_username:   d5c8b784c1d0
segmentfault_username:   nojsja

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Sidebar settings
sidebar: true                      # whether or not using Sidebar.
sidebar-about-description: "Stay hungry, Stay foolish"
sidebar-avatar: img/avatar/nojsja.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- search
- short-about
- featured-tags
# - visitor
- recent-posts
- friends-blog
# - archive
# - category

## Search
search:
  enable: true
  path: search.xml
  field: post
  content: true

# widget behavior
## Archive
archives-img: img/header_img/archives-widget.jpg
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value


## Friends
friends: [
    {
        title: "Leancloud",
        href: "https://www.leancloud.cn/"
    },
    {
        title: "Valine",
        href: "https://valine.js.org/"
    },
    {
        title: "GnomeLook",
        href: "https://www.gnome-look.org/browse/cat/"
    },
    {
        title: "Npm",
        href: "https://www.npmjs.com/settings/nojsja/packages"
    },
]


math:
  enable: true
  engine: mathjax

#Custom Setting End

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
include:
- ".github/**/*"
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'

  plugins:
    - markdown-it-abbr
    - markdown-it-mark
    - markdown-it-container
    - markdown-it-emoji
    - name: markdown-it-task-lists
      options:
        enabled: true
        label: true
        labelAfter: false
  
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: snail

#sitemap
sitemap:
  path: sitemap.xml
## Baidusitemap
baidusitemap:
path: baidusitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/nojsja/blogs
  # repository: https://gitee.com/nojsja/blogs
  # repository: https://e.coding.net/nojsja/blogs/blogs.git
  branch: master
  ignore_hidden:
    public: false
  message: update

## share
share: false

# Comment
## This comment system is gitment
comment:
  valine:
    enable: true
    appId: "wUKKBx8BRzGaNfhgdg2UKtub-MdYXbMMI"
    appKey: "MAwYM4KlW5YJ3q06qwnUScBr"
    notify: false
    verify: false
    visitor: true
    avatar: 'mm' # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
    pageSize: 10
    placeholder: 'just go go' # Comment Box placeholder
    background:

## music
### netease; qqkg;
### if your `library` is `qqkg`, please set `music` as the song url
music:
  enable: true
  library: netease
  music: https://kg.qq.com/node/play?s=7deFpz7Z26Jmv7di&g_f=share_html

# Tip
tip:
  enable: true
  copyright: Copyright © nojsja 2020
  content: false

# Background effects
## If there is no effect after modification, please empty the cache and try again.
## ⚠️ The following special effects will take up a lot of cpu resorces, please open it carefully.
bg_effects:
  enable: true
  wave:
    enable: true

# Color Theme
## light , dark or star
## If you set the value of the `color_theme` to `dark`, set the value of the `highlight_theme` to `night` in `/theme/snail/config.yml`
## `mouse_control` is only valid for star themes
color_theme: light
mouse_control: false

# Visitor statistics
visitor:
  enable: true
  type:

# Chinese Blog
chinese_blog:
  enable: false
  url: YOUR_CHINESE_BLOG_URL

# ---- 代码和资源压缩
html_minifier:
  enable: true
  exclude:

css_minifier:
  enable: true
  exclude: 
    - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  compress: true
  exclude: 
    - '*.min.js'

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

# ---- 图片懒加载
image_lazy:
  enable: true
  type: post
  replacement: "/blogs/img/loading.gif"

# ---- 外链减少权重
nofollow:
  enable: true #是否启用插件，默认值为 true
  field: site #插件的处理范围，默认值为 site，可选 post 或 site
  exclude: #域名白名单
    - 'nojsja.gitee.io'
    - 'nojsja.github.io'

favicon: /blogs/img/favicon.ico